services:

  order-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_MULTIPLE_DATABASES="order-service-db","myuser": "inventory-service-db","myuser"'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  product-db:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=product-service-db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'

  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
    ports:
      - '8181:8080'
    command: 'start-dev'


    #  inventory-db:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=inventory-service-db'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myinventoryuser'
#    ports:
#      - '5433:5433'